apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kube-reqsizer.fullname" . }}-controller-manager
  labels:
    control-plane: controller-manager
  {{- include "kube-reqsizer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controllerManager.replicas }}
  selector:
    matchLabels:
      control-plane: controller-manager
    {{- include "kube-reqsizer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        control-plane: controller-manager
      {{- include "kube-reqsizer.selectorLabels" . | nindent 8 }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: '8080'
        reqsizer.jatalocks.github.io/optimize: 'false'      
    spec:
      containers:
      - args:
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=:8080
        - --leader-elect
        - --annotation-filter={{.Values.enabledAnnotation}}
        - --sample-size={{.Values.sampleSize}}
        - --min-seconds={{.Values.minSeconds}}
        - --zap-log-level={{.Values.logLevel}}
        - --enable-increase={{.Values.enableIncrease}}
        - --enable-reduce={{.Values.enableReduce}}
        - --max-cpu={{.Values.maxCPU}}
        - --max-memory={{.Values.maxMemory}}
        - --min-cpu={{.Values.minCPU}}
        - --min-memory={{.Values.minMemory}}
        - --cpu-factor={{.Values.cpuFactor}}
        - --memory-factor={{.Values.memoryFactor}}        
        - --concurrent-workers={{.Values.concurrentWorkers}}
        - --enable-persistence={{.Values.persistence.enabled}}        
        - --redis-host={{.Release.Name}}-redis-master
        resources:
          {{- toYaml .Values.controllerManager.manager.resources | nindent 10 }}
        command:
        - /manager
        env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ .Values.kubernetesClusterDomain }}
        ports:
        - name: metrics
          containerPort: {{ .Values.metricsService.port }}
        image: {{ .Values.controllerManager.manager.image.repository }}:{{ .Values.controllerManager.manager.image.tag }}
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        securityContext:
          allowPrivilegeEscalation: false
      securityContext:
        runAsUser: 65532
      terminationGracePeriodSeconds: 10