apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kube-reqsizer.fullname" . }}-manager-role
  labels:
  {{- include "kube-reqsizer.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - "*"
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - "apps"
  resources:
  - "*"
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods", "nodes"]
  verbs: ["get", "list", "watch"]  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kube-reqsizer.fullname" . }}-manager-rolebinding
  labels:
  {{- include "kube-reqsizer.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "kube-reqsizer.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: default
  namespace: '{{ .Release.Namespace }}'