apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-reqsizer.fullname" . }}-controller-manager-metrics-service
  labels:
    control-plane: controller-manager
  {{- include "kube-reqsizer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metricsService.type }}
  selector:
    control-plane: controller-manager
  {{- include "kube-reqsizer.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.metricsService.port }}
      targetPort: metrics  