# Prometheus Monitor Service (Metrics)
{{ if .Values.serviceMonitor }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    control-plane: controller-manager
    release: prometheusoperator
  name: controller-manager-metrics-monitor
spec:
  jobLabel: kube-reqsizer-servicemonitor
  endpoints:
    - path: /metrics
      port: metrics
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      control-plane: controller-manager
{{ end }}
