sampleSize: 1
minSeconds: 1
enabledAnnotation: true
logLevel: info

controllerManager:
  kubeRbacProxy:
    image:
      repository: gcr.io/kubebuilder/kube-rbac-proxy
      tag: v0.5.0
  manager:
    image:
      repository: jatalocks333/kube-reqsizer
      tag: latest
    resources:
      limits:
        cpu: 2
        memory: 5Gi
      requests:
        cpu: 0.5
        memory: 100Mi
  replicas: 1
kubernetesClusterDomain: cluster.local
managerConfig:
  controllerManagerConfigYaml:
    health:
      healthProbeBindAddress: :8081
    leaderElection:
      leaderElect: true
      resourceName: d84d636a.kube-reqsizer
    metrics:
      bindAddress: 127.0.0.1:8080
    webhook:
      port: 9443
metricsService:
  ports:
  - name: https
    port: 8443
    targetPort: https
  type: ClusterIP
