sampleSize: 1
minSeconds: 1
enabledAnnotation: false
logLevel: info
# Namespace annotation filter
# Scale up / scale down requests
# Timestamp per sample to restrict pod restarts

controllerManager:
  kubeRbacProxy:
    image:
      repository: gcr.io/kubebuilder/kube-rbac-proxy
      tag: v0.5.0
  manager:
    image:
      repository: jatalocks333/kube-reqsizer
      tag: latest
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 20Mi
  replicas: 1
kubernetesClusterDomain: cluster.local
managerConfig:
  controllerManagerConfigYaml:
    health:
      healthProbeBindAddress: :8081
    leaderElection:
      leaderElect: true
      resourceName: d84d636a.kube-reqsizer
    metrics:
      bindAddress: 127.0.0.1:8080
    webhook:
      port: 9443
metricsService:
  ports:
  - name: https
    port: 8443
    targetPort: https
  type: ClusterIP
