name: Test and coverage

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.19.x]
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: go get
        run: go get ./...

      - name: go mod tidy
        run: go mod tidy

      - name: Run coverage
        run: go test -race -coverprofile=coverage.out -covermode=atomic ./...

      - name: Upload coverage to Codecov
        if: matrix.os == 'ubuntu-latest'
        run: bash <(curl -s https://codecov.io/bash)